<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <AssemblyName>ShaderNightVision</AssemblyName>
        <Product>ShaderNightVision</Product>
        <Version>1.0.0</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
            https://nuget.samboy.dev/v3/index.json
        </RestoreAdditionalProjectSources>
        <RootNamespace>ShaderNightVision</RootNamespace>
        <AssemblyVersion>1.1.0</AssemblyVersion>
        <FileVersion>1.1.0</FileVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all"/>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.5.0-beta.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="BepInEx.Core" Version="5.*"/>
        <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Assembly-CSharp" Publicize="True">
        <HintPath>Assemblies\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp-firstpass">
        <HintPath>Assemblies\Assembly-CSharp-firstpass.dll</HintPath>
      </Reference>
      <Reference Include="ConfigurationManager">
        <HintPath>Assemblies\ConfigurationManager.dll</HintPath>
      </Reference>
      <Reference Include="Mirage">
        <HintPath>Assemblies\Mirage.dll</HintPath>
      </Reference>
      <Reference Include="Rewired_Core">
        <HintPath>Assemblies\Rewired_Core.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipeline.Universal.ShaderLibrary">
        <HintPath>Assemblies\Unity.RenderPipeline.Universal.ShaderLibrary.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Core.Runtime">
        <HintPath>Assemblies\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Core.ShaderLibrary">
        <HintPath>Assemblies\Unity.RenderPipelines.Core.ShaderLibrary.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary">
        <HintPath>Assemblies\Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Universal.2D.Internal">
        <HintPath>Assemblies\Unity.RenderPipelines.Universal.2D.Internal.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Universal.Config.Runtime">
        <HintPath>Assemblies\Unity.RenderPipelines.Universal.Config.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Universal.Runtime">
        <HintPath>Assemblies\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Universal.Shaders">
        <HintPath>Assemblies\Unity.RenderPipelines.Universal.Shaders.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>Assemblies\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AssetBundleModule">
        <HintPath>Assemblies\UnityEngine.AssetBundleModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>Assemblies\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.InputLegacyModule">
        <HintPath>Assemblies\UnityEngine.InputLegacyModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>Assemblies\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIModule">
        <HintPath>Assemblies\UnityEngine.UIModule.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <None Remove="EmbeddedResources\shadernv" />
      <EmbeddedResource Include="EmbeddedResources\shadernv" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Assets\icon\" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="xcopy /q/y/i &quot;$(TargetPath)&quot; &quot;D:\SteamLibrary\steamapps\common\Nuclear Option\BepInEx\plugins\$(TargetName)-v$(AssemblyVersion).d*&quot; /E /H /C&#xA;" />
    </Target>
</Project>
